In [1]:
import pandas as pd

In [2]:
data={'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [3]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [4]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [7]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [8]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df['Name']

0    Alice
1      Bob
Name: Name, dtype: object

In [9]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [11]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [12]:
df[df ['Age']>25]

  Name  Age
1  Bob   30

In [14]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df['Gender'] = ['F', 'M']
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [15]:
lst=[['Alice', 25], ['Bob', 30]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df['Gender'] = ['F', 'M']
df.drop('Age', axis=1, inplace=True)
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [16]:
lst=[['Alice', 25], ['Bob', ]]
df=pd.DataFrame(lst, columns=['Name', 'Age'])
df.isnull()

    Name    Age
0  False  False
1  False   True

In [17]:
df.dropna()

    Name   Age
0  Alice  25.0

In [18]:
df.fillna(30)

    Name   Age
0  Alice  25.0
1    Bob  30.0

In [19]:
df.groupby('Age')

In [24]:
df1 = pd.DataFrame({'key': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'key': [1, 2, 4], 'Age': [25, 30, 40]})
result = pd.merge(df1, df2, on='key')
print(result)

   key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [23]:
df.to_csv('output.csv', index=False)
print(df)

    Name   Age
0  Alice  25.0
1    Bob   NaN

In [27]:
df.sort_values('Age')

    Name   Age
0  Alice  25.0
1    Bob   NaN

In [28]:
df['Age'].apply(lambda x: x + 1)

0    26.0
1     NaN
Name: Age, dtype: float64

In [29]:
df['Name'].unique()

array(['Alice', 'Bob'], dtype=object)

In [30]:
df['Age'].value_counts()

Age
25.0    1
Name: count, dtype: int64